pandoc ./gastrointestinal-disease-simulation.md -o ./gastrointestinal-disease-simulation.docx 
pandoc ./normalize-criteria-values.md -o ./normalize-criteria-values.docx
pandoc ./take-action1.md -o ./take-action1.docx
pandoc ./flooding-simulation.md -o ./flooding-simulation.docx
pandoc ./weekly1.md -o ./weekly1.docx
pandoc ./site-selection.md -o ./site-selection.docx
pandoc ./update-census-block-attributes1.md -o ./update-census-block-attributes1.docx
pandoc ./annual2.md -o ./annual2.docx
pandoc ./annual.md -o ./annual.docx
pandoc ./subsidence.md -o ./subsidence.docx
pandoc ./water-supply-simulation.md -o ./water-supply-simulation.docx
pandoc ./read-flooding-events-write-disease-incidence.md -o ./read-flooding-events-write-disease-incidence.docx
pandoc ./monthly.md -o ./monthly.docx
pandoc ./read-age-sewer-capacity-writes-flooding-events-per-year.md -o ./read-age-sewer-capacity-writes-flooding-events-per-year.docx
pandoc ./normalize-criteria-values1.md -o ./normalize-criteria-values1.docx
pandoc ./annual3.md -o ./annual3.docx
pandoc ./annual1.md -o ./annual1.docx
pandoc ./water-extraction-write-subsidence-rate.md -o ./water-extraction-write-subsidence-rate.docx
pandoc ./weekly.md -o ./weekly.docx
pandoc ./water-operator.md -o ./water-operator.docx
pandoc ./take-action.md -o ./take-action.docx
pandoc ./calculate-distances-to-ideal-points1.md -o ./calculate-distances-to-ideal-points1.docx
pandoc ./update-census-block-attributes.md -o ./update-census-block-attributes.docx
pandoc ./monthly1.md -o ./monthly1.docx
pandoc ./calculate-distances-to-ideal-points.md -o ./calculate-distances-to-ideal-points.docx
pandoc ./residents.md -o ./residents.docx
pandoc ./census-blocks.md -o ./census-blocks.docx
pandoc ./update-census-block-number-of-days-wo-water.md -o ./update-census-block-number-of-days-wo-water.docx
